AWSTemplateFormatVersion: "2010-09-09"
Description: Internal Template - Generate link based on EC2 outputs

Parameters:
  QualixIP:
    Type: String

  Protocol:
    Type: String
    AllowedValues: ["rdp", "ssh"]

  ConnectionPort:
    Type: Number

  TargetIPAddress:
    Type: String

  TargetUsernameSSMParameter:
    Type: String

  TargetPasswordSSMParameter:
    Type: String

Resources:
  TargetUsername:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Properties:
      Name: !Ref TargetUsernameSSMParameter

  TargetPassword:
    Type: 'AWS::SSM::Parameter::Value<String>'
    Properties:
      Name: !Ref TargetPasswordSSMParameter

Outputs:
  HttpLink:
    Value:
      Fn::Sub: "https://${QualixIP}/remote/#/client/c/${Protocol}${ResourceUUID}?qtoken=${Token}&hostname=${TargetIPAddress}&protocol=${Protocol}&port=${ConnectionPort}&username=${TargetUsername}&password=${TargetPassword}${ExtraAttributes}"

