AWSTemplateFormatVersion: '2010-09-09'
Description: Create Ubuntu EC2 instance 
Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-ubuntu-latest/ubuntu-ami-hvm-x86_64-gp2'

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - sg-0d89d6d91b4e2bfb0
      SubnetId: subnet-024852156a24074fa
      UserData: !Base64
        Fn::Sub: |
          #!/bin/bash
          sudo echo "ubuntu:1234" | chpasswd
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service sshd restart

Outputs:
  MyEC2InstancePublicIP:
    Value: !GetAtt MyEC2Instance.PublicIp         

# AWSTemplateFormatVersion: '2010-09-09'
# Description: Create an EC2 instance

# Parameters:
#   LatestAmiId:
#     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
#     Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

# Resources:
#   MyEC2Instance:
#     Type: AWS::EC2::Instance
#     Properties:
#       InstanceType: t2.micro
#       ImageId: !Ref LatestAmiId

# Outputs:
#   MyEC2InstancePublicIP:
#     Value: !GetAtt MyEC2Instance.PublicIp
